---
- name: Installing maildev
  npm:
    name: maildev
    global: yes
  when: npm_global_packages.stdout is not search('maildev')

- name: Setup maildev as a supervisor deamon
  template:
    src: supervisor-maildev.conf
    dest: /opt/homebrew/share/supervisor/conf.d/maildev.conf
  notify:
    - Restart supervisord